
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = gasmf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE   = libpetscksp
LOCDIR    = src/ksp/pc/impls/gasm/ftn-auto/
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
