
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = dflushf.c drawregf.c dclearf.c dtextf.c dpointf.c dviewpf.c dcoorf.c dlinef.c dpausef.c dsavef.c dmarkerf.c dellipsef.c drectf.c dtrif.c dmousef.c drawf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE   = libpetscsys
LOCDIR    = src/sys/classes/draw/interface/ftn-auto/
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
