
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = snesshellf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetscsnes
LOCDIR   = src/snes/impls/shell/ftn-auto/
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
