
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib
CPPFLAGS =
CFLAGS   =
FFLAGS   =
SOURCEC  = sundialsf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetscts
LOCDIR   = src/ts/impls/implicit/sundials/ftn-auto/
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
