
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib
CPPFLAGS =
CFLAGS   =
FFLAGS   =
SOURCEC  = sbaijf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE	 = libpetscmat
LOCDIR	 = src/mat/impls/sbaij/seq/ftn-auto/
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
