
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib
CPPFLAGS  = ${SCOTCH_INCLUDE}
CFLAGS   =
FFLAGS   =
SOURCEC  = scotchf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE   = libpetscmat
LOCDIR    = src/mat/partition/impls/scotch/ftn-auto/
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
