
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = generalf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE   = libpetscvec
LOCDIR    = src/vec/is/is/impls/general/ftn-auto/
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
