
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib
CPPFLAGS  = ${SPAI_INCLUDE}
CFLAGS   =
FFLAGS   =
SOURCEC  = ispaif.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE   = libpetscksp
LOCDIR    = src/ksp/pc/impls/spai/ftn-auto/
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
