
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib
CPPFLAGS  = ${PARTY_INCLUDE}
CFLAGS   =
FFLAGS   =
SOURCEC  = partyf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE   = libpetscmat
LOCDIR    = src/mat/partition/impls/party/ftn-auto/
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
