        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 27 17:35:32 2016
        MODULE DD_PREPARE__genmod
          INTERFACE 
            SUBROUTINE DD_PREPARE(LUNUT,NMAX,MMAX,LGRID,NBMAX,NDOMS,    &
     &NBNDS,NCONN,DOMS,BNDS,CONN)
              USE TYPOS
              INTEGER(KIND=4), INTENT(IN) :: NBNDS
              INTEGER(KIND=4), INTENT(IN) :: NDOMS
              INTEGER(KIND=4), INTENT(IN) :: MMAX
              INTEGER(KIND=4), INTENT(IN) :: NMAX
              INTEGER(KIND=4), INTENT(IN) :: LUNUT
              INTEGER(KIND=4), INTENT(INOUT) :: LGRID(NMAX,MMAX)
              INTEGER(KIND=4), INTENT(IN) :: NBMAX
              INTEGER(KIND=4), INTENT(OUT) :: NCONN
              TYPE (DOMAIN), INTENT(IN) :: DOMS(NDOMS)
              TYPE (BOUNDP), INTENT(IN) :: BNDS(NBNDS)
              TYPE (PNT) ,POINTER :: CONN(:)
            END SUBROUTINE DD_PREPARE
          END INTERFACE 
        END MODULE DD_PREPARE__genmod
