        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 27 17:35:52 2016
        MODULE DLWQTD__genmod
          INTERFACE 
            SUBROUTINE DLWQTD(LUNIN,LUNOUT,ITIME,IDTIME,ITIME1,ITIME2,  &
     &NFTOT,NRTOT,ARRAY1,ARRAY2,RESULT,IPNT,LBLOCK,LUNTXT,ISFLAG,IFFLAG,&
     &UPDATE)
              INTEGER(KIND=4), INTENT(IN) :: NRTOT
              INTEGER(KIND=4), INTENT(IN) :: NFTOT
              INTEGER(KIND=4), INTENT(IN) :: LUNIN
              INTEGER(KIND=4), INTENT(IN) :: LUNOUT
              INTEGER(KIND=4), INTENT(IN) :: ITIME
              INTEGER(KIND=4), INTENT(INOUT) :: IDTIME
              INTEGER(KIND=4), INTENT(INOUT) :: ITIME1
              INTEGER(KIND=4), INTENT(INOUT) :: ITIME2
              REAL(KIND=4), INTENT(INOUT) :: ARRAY1(NFTOT)
              REAL(KIND=4), INTENT(INOUT) :: ARRAY2(NFTOT)
              REAL(KIND=4), INTENT(INOUT) :: RESULT(NRTOT)
              INTEGER(KIND=4), INTENT(IN) :: IPNT(NFTOT)
              LOGICAL(KIND=4), INTENT(IN) :: LBLOCK
              CHARACTER(*), INTENT(IN) :: LUNTXT
              INTEGER(KIND=4), INTENT(IN) :: ISFLAG
              INTEGER(KIND=4), INTENT(IN) :: IFFLAG
              LOGICAL(KIND=4), INTENT(OUT) :: UPDATE
            END SUBROUTINE DLWQTD
          END INTERFACE 
        END MODULE DLWQTD__genmod
