        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 27 17:35:56 2016
        MODULE DLWQBL__genmod
          INTERFACE 
            SUBROUTINE DLWQBL(LUNIN,LUNOUT,ITIME,IDTIME,ITIME1,ITIME2,  &
     &IHDEL,NFTOT,NRTOT,ARRAY1,RESULT,IPNT,LUNTXT,ISFLAG,IFFLAG,UPDATE)
              INTEGER(KIND=4), INTENT(IN) :: NRTOT
              INTEGER(KIND=4), INTENT(IN) :: NFTOT
              INTEGER(KIND=4), INTENT(IN) :: LUNIN
              INTEGER(KIND=4), INTENT(IN) :: LUNOUT
              INTEGER(KIND=4), INTENT(IN) :: ITIME
              INTEGER(KIND=4), INTENT(INOUT) :: IDTIME
              INTEGER(KIND=4), INTENT(INOUT) :: ITIME1
              INTEGER(KIND=4), INTENT(INOUT) :: ITIME2
              INTEGER(KIND=4), INTENT(IN) :: IHDEL
              REAL(KIND=4), INTENT(INOUT) :: ARRAY1(NFTOT)
              REAL(KIND=4), INTENT(INOUT) :: RESULT(NRTOT)
              INTEGER(KIND=4), INTENT(IN) :: IPNT(NFTOT)
              CHARACTER(*), INTENT(IN) :: LUNTXT
              INTEGER(KIND=4), INTENT(IN) :: ISFLAG
              INTEGER(KIND=4), INTENT(IN) :: IFFLAG
              LOGICAL(KIND=4), INTENT(OUT) :: UPDATE
            END SUBROUTINE DLWQBL
          END INTERFACE 
        END MODULE DLWQBL__genmod
