        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 27 17:35:23 2016
        MODULE DOCLOSE__genmod
          INTERFACE 
            SUBROUTINE DOCLOSE(MINP)
              INTEGER(KIND=4), INTENT(INOUT) :: MINP
            END SUBROUTINE DOCLOSE
          END INTERFACE 
        END MODULE DOCLOSE__genmod
