        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 27 17:35:23 2016
        MODULE EOFERROR__genmod
          INTERFACE 
            SUBROUTINE EOFERROR(MINP)
              INTEGER(KIND=4), INTENT(IN) :: MINP
            END SUBROUTINE EOFERROR
          END INTERFACE 
        END MODULE EOFERROR__genmod
