        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 27 17:36:28 2016
        MODULE GET_VALID_LINE__genmod
          INTERFACE 
            FUNCTION GET_VALID_LINE(LUN,LUNPR)
              INTEGER(KIND=4) :: LUN
              INTEGER(KIND=4) :: LUNPR
              CHARACTER(LEN=200) :: GET_VALID_LINE
            END FUNCTION GET_VALID_LINE
          END INTERFACE 
        END MODULE GET_VALID_LINE__genmod
