        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 27 17:35:57 2016
        MODULE GETDIM_ASC__genmod
          INTERFACE 
            SUBROUTINE GETDIM_ASC(LUN,ASC_FILE,NPART_INI,NROWSMAX,LUNLOG&
     &)
              INTEGER(KIND=4) :: LUN
              CHARACTER(LEN=256) :: ASC_FILE
              INTEGER(KIND=4) :: NPART_INI
              INTEGER(KIND=4) :: NROWSMAX
              INTEGER(KIND=4) :: LUNLOG
            END SUBROUTINE GETDIM_ASC
          END INTERFACE 
        END MODULE GETDIM_ASC__genmod
