        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 27 17:35:57 2016
        MODULE GETDIM_INI__genmod
          INTERFACE 
            SUBROUTINE GETDIM_INI(LUN,INI_FILE,NPART_INI,NPOLMAX,       &
     &NROWSMAX,LUNLOG)
              INTEGER(KIND=4) :: LUN
              CHARACTER(LEN=256) :: INI_FILE
              INTEGER(KIND=4) :: NPART_INI
              INTEGER(KIND=4) :: NPOLMAX
              INTEGER(KIND=4) :: NROWSMAX
              INTEGER(KIND=4) :: LUNLOG
            END SUBROUTINE GETDIM_INI
          END INTERFACE 
        END MODULE GETDIM_INI__genmod
