        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 27 17:35:55 2016
        MODULE GETDPS__genmod
          INTERFACE 
            SUBROUTINE GETDPS(LUNPR,LUNDP,LNAM,NMAX,MMAX,NOSEGL,DPS,    &
     &CELLPNT,LTRACK)
              INTEGER(KIND=4), INTENT(IN) :: NOSEGL
              INTEGER(KIND=4), INTENT(IN) :: MMAX
              INTEGER(KIND=4), INTENT(IN) :: NMAX
              INTEGER(KIND=4), INTENT(IN) :: LUNPR
              INTEGER(KIND=4), INTENT(IN) :: LUNDP
              CHARACTER(*), INTENT(IN) :: LNAM
              REAL(KIND=4), INTENT(OUT) :: DPS(NMAX*MMAX)
              INTEGER(KIND=4), INTENT(IN) :: CELLPNT(NOSEGL)
              LOGICAL(KIND=4), INTENT(IN) :: LTRACK
            END SUBROUTINE GETDPS
          END INTERFACE 
        END MODULE GETDPS__genmod
