        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 27 17:35:57 2016
        MODULE GETDIM_DIS__genmod
          INTERFACE 
            SUBROUTINE GETDIM_DIS(LUN,DIS_FILE,NROWSMAX,LUNLOG)
              INTEGER(KIND=4) :: LUN
              CHARACTER(LEN=256) :: DIS_FILE
              INTEGER(KIND=4) :: NROWSMAX
              INTEGER(KIND=4) :: LUNLOG
            END SUBROUTINE GETDIM_DIS
          END INTERFACE 
        END MODULE GETDIM_DIS__genmod
