        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 27 17:35:23 2016
        MODULE IFIRSTCHAR__genmod
          INTERFACE 
            FUNCTION IFIRSTCHAR(REC)
              CHARACTER(*), INTENT(IN) :: REC
              INTEGER(KIND=4) :: IFIRSTCHAR
            END FUNCTION IFIRSTCHAR
          END INTERFACE 
        END MODULE IFIRSTCHAR__genmod
