        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 27 17:35:23 2016
        MODULE IFIRSTLETTER__genmod
          INTERFACE 
            FUNCTION IFIRSTLETTER(REC)
              CHARACTER(*) :: REC
              INTEGER(KIND=4) :: IFIRSTLETTER
            END FUNCTION IFIRSTLETTER
          END INTERFACE 
        END MODULE IFIRSTLETTER__genmod
