        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 27 17:35:23 2016
        MODULE ILOCATESTRING__genmod
          INTERFACE 
            SUBROUTINE ILOCATESTRING(REC,I1,I2)
              CHARACTER(*), INTENT(IN) :: REC
              INTEGER(KIND=4), INTENT(OUT) :: I1
              INTEGER(KIND=4), INTENT(OUT) :: I2
            END SUBROUTINE ILOCATESTRING
          END INTERFACE 
        END MODULE ILOCATESTRING__genmod
