        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 27 17:35:23 2016
        MODULE NEWFIL__genmod
          INTERFACE 
            SUBROUTINE NEWFIL(MINP,FILENAME)
              INTEGER(KIND=4), INTENT(OUT) :: MINP
              CHARACTER(*), INTENT(IN) :: FILENAME
            END SUBROUTINE NEWFIL
          END INTERFACE 
        END MODULE NEWFIL__genmod
