        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 27 17:35:23 2016
        MODULE OLDFIL__genmod
          INTERFACE 
            SUBROUTINE OLDFIL(MINP,FILENAME)
              INTEGER(KIND=4), INTENT(OUT) :: MINP
              CHARACTER(*), INTENT(IN) :: FILENAME
            END SUBROUTINE OLDFIL
          END INTERFACE 
        END MODULE OLDFIL__genmod
