        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 27 17:35:57 2016
        MODULE OPEN_INIFILE__genmod
          INTERFACE 
            SUBROUTINE OPEN_INIFILE(LUN,FINAM,FTYPE)
              INTEGER(KIND=4) :: LUN
              CHARACTER(LEN=256) :: FINAM
              CHARACTER(LEN=20) :: FTYPE
            END SUBROUTINE OPEN_INIFILE
          END INTERFACE 
        END MODULE OPEN_INIFILE__genmod
