        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 27 17:36:31 2016
        MODULE PART08__genmod
          INTERFACE 
            SUBROUTINE PART08(LUN,NODYE,NOCONT,ICTMAX,AMASSD,ICTIME,    &
     &AMASSC,ACONC,TMASS,TMASSC,NOSUBS,NDPRT,TMASSU,FTIME,LINEAR,SUBSTI,&
     &NMDYER,NMCONR)
              INTEGER(KIND=4), INTENT(IN) :: NOSUBS
              INTEGER(KIND=4), INTENT(IN) :: NOCONT
              INTEGER(KIND=4), INTENT(IN) :: NODYE
              INTEGER(KIND=4), INTENT(IN) :: LUN
              INTEGER(KIND=4), INTENT(IN) :: ICTMAX(NOCONT)
              REAL(KIND=4), INTENT(IN) :: AMASSD(NOSUBS,NODYE)
              INTEGER(KIND=4), INTENT(IN) :: ICTIME(NOCONT,*)
              REAL(KIND=4), INTENT(IN) :: AMASSC(NOCONT,NOSUBS,*)
              REAL(KIND=4), INTENT(OUT) :: ACONC(NODYE+NOCONT,NOSUBS)
              REAL(KIND=4), INTENT(OUT) :: TMASS(NOSUBS)
              REAL(KIND=4), INTENT(OUT) :: TMASSC(NOCONT,NOSUBS)
              INTEGER(KIND=4), INTENT(IN) :: NDPRT(NODYE+NOCONT)
              REAL(KIND=4), INTENT(OUT) :: TMASSU(NOCONT)
              REAL(KIND=4), INTENT(IN) :: FTIME(NOCONT,*)
              INTEGER(KIND=4), INTENT(IN) :: LINEAR(NOCONT)
              CHARACTER(*), INTENT(IN) :: SUBSTI(NOSUBS)
              CHARACTER(*), INTENT(IN) :: NMDYER(NODYE)
              CHARACTER(*), INTENT(IN) :: NMCONR(NOCONT)
            END SUBROUTINE PART08
          END INTERFACE 
        END MODULE PART08__genmod
