        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 27 17:36:34 2016
        MODULE PART15__genmod
          INTERFACE 
            SUBROUTINE PART15(LUNPR,ITIME,SPAWND,NOSEG,NOWIND,IWNDTM,   &
     &WVELOA,WDIRA,WVELO,WDIR)
              INTEGER(KIND=4), INTENT(IN) :: NOWIND
              INTEGER(KIND=4), INTENT(IN) :: NOSEG
              INTEGER(KIND=4), INTENT(IN) :: LUNPR
              INTEGER(KIND=4), INTENT(IN) :: ITIME
              LOGICAL(KIND=4), INTENT(IN) :: SPAWND
              INTEGER(KIND=4), INTENT(IN) :: IWNDTM(NOWIND)
              REAL(KIND=4), INTENT(IN) :: WVELOA(NOWIND)
              REAL(KIND=4), INTENT(IN) :: WDIRA(NOWIND)
              REAL(KIND=8), INTENT(OUT) :: WVELO(NOSEG)
              REAL(KIND=8), INTENT(OUT) :: WDIR(NOSEG)
            END SUBROUTINE PART15
          END INTERFACE 
        END MODULE PART15__genmod
