        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 27 17:36:33 2016
        MODULE PART06__genmod
          INTERFACE 
            SUBROUTINE PART06(LUN,LGRID,LGRID2,NMAX,MMAX,XB,YB,NODYE,   &
     &NOCONT,XWASTE,YWASTE,NWASTE,MWASTE)
              INTEGER(KIND=4), INTENT(IN) :: NOCONT
              INTEGER(KIND=4), INTENT(IN) :: NODYE
              INTEGER(KIND=4), INTENT(IN) :: MMAX
              INTEGER(KIND=4), INTENT(IN) :: NMAX
              INTEGER(KIND=4), INTENT(IN) :: LUN
              INTEGER(KIND=4), INTENT(IN) :: LGRID(NMAX,MMAX)
              INTEGER(KIND=4), INTENT(IN) :: LGRID2(NMAX,MMAX)
              REAL(KIND=4), INTENT(IN) :: XB(NMAX*MMAX)
              REAL(KIND=4), INTENT(IN) :: YB(NMAX*MMAX)
              REAL(KIND=4), INTENT(INOUT) :: XWASTE(NODYE+NOCONT)
              REAL(KIND=4), INTENT(INOUT) :: YWASTE(NODYE+NOCONT)
              INTEGER(KIND=4), INTENT(OUT) :: NWASTE(NODYE+NOCONT)
              INTEGER(KIND=4), INTENT(OUT) :: MWASTE(NODYE+NOCONT)
            END SUBROUTINE PART06
          END INTERFACE 
        END MODULE PART06__genmod
