        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 27 17:36:34 2016
        MODULE PARTVS__genmod
          INTERFACE 
            SUBROUTINE PARTVS(LUN2,ITIME,NOSUBS,NOPART,IVTSET,IVTIME,   &
     &VSFOUR,VSFACT,WPART,WSETTL,MODTYP,NMAX,MMAX,LGRID3,NOLAY,NPART,   &
     &MPART,KPART,NOSEGP,NOSEGLP,RHOPART,RHOWATC,SPART,IPTIME)
              INTEGER(KIND=4), INTENT(IN) :: NOSEGP
              INTEGER(KIND=4), INTENT(IN) :: MMAX
              INTEGER(KIND=4), INTENT(IN) :: NMAX
              INTEGER(KIND=4), INTENT(IN) :: IVTSET
              INTEGER(KIND=4), INTENT(IN) :: NOPART
              INTEGER(KIND=4), INTENT(IN) :: NOSUBS
              INTEGER(KIND=4), INTENT(IN) :: LUN2
              INTEGER(KIND=4), INTENT(IN) :: ITIME
              INTEGER(KIND=4), INTENT(IN) :: IVTIME(IVTSET)
              REAL(KIND=4), INTENT(IN) :: VSFOUR(6,NOSUBS,IVTSET)
              REAL(KIND=4) :: VSFACT(6,NOSUBS)
              REAL(KIND=4), INTENT(IN) :: WPART(NOSUBS,NOPART)
              REAL(KIND=4), INTENT(OUT) :: WSETTL(NOPART)
              INTEGER(KIND=4), INTENT(IN) :: MODTYP
              INTEGER(KIND=4), INTENT(IN) :: LGRID3(NMAX,MMAX)
              INTEGER(KIND=4), INTENT(IN) :: NOLAY
              INTEGER(KIND=4), INTENT(IN) :: NPART(NOPART)
              INTEGER(KIND=4), INTENT(IN) :: MPART(NOPART)
              INTEGER(KIND=4), INTENT(IN) :: KPART(NOPART)
              INTEGER(KIND=4), INTENT(IN) :: NOSEGLP
              REAL(KIND=4), INTENT(IN) :: RHOPART(NOSUBS,NOPART)
              REAL(KIND=4), INTENT(IN) :: RHOWATC(NOSEGP)
              REAL(KIND=4), INTENT(IN) :: SPART(NOSUBS,*)
              INTEGER(KIND=4), INTENT(IN) :: IPTIME(NOPART)
            END SUBROUTINE PARTVS
          END INTERFACE 
        END MODULE PARTVS__genmod
