        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 27 17:36:28 2016
        MODULE PART01__genmod
          INTERFACE 
            SUBROUTINE PART01(LGRID,LGRID2,XP,YP,DX,DY,AREA,ANGLE,NMAX, &
     &MMAX)
              INTEGER(KIND=4), INTENT(IN) :: MMAX
              INTEGER(KIND=4), INTENT(IN) :: NMAX
              INTEGER(KIND=4), INTENT(IN) :: LGRID(NMAX,MMAX)
              INTEGER(KIND=4), INTENT(IN) :: LGRID2(NMAX,MMAX)
              REAL(KIND=4), INTENT(IN) :: XP(NMAX*MMAX)
              REAL(KIND=4), INTENT(IN) :: YP(NMAX*MMAX)
              REAL(KIND=4), INTENT(OUT) :: DX(NMAX*MMAX)
              REAL(KIND=4), INTENT(OUT) :: DY(NMAX*MMAX)
              REAL(KIND=4), INTENT(OUT) :: AREA(NMAX*MMAX)
              REAL(KIND=4), INTENT(OUT) :: ANGLE(NMAX*MMAX)
            END SUBROUTINE PART01
          END INTERFACE 
        END MODULE PART01__genmod
