        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 27 17:36:30 2016
        MODULE PLOTGRP__genmod
          INTERFACE 
            SUBROUTINE PLOTGRP(NPGRID,PG,NMAX,MMAX,LGRID,LGRID2,XB,YB)
              USE TYPOS
              INTEGER(KIND=4), INTENT(IN) :: MMAX
              INTEGER(KIND=4), INTENT(IN) :: NMAX
              INTEGER(KIND=4), INTENT(IN) :: NPGRID
              TYPE (PLOTGRID) :: PG(NPGRID)
              INTEGER(KIND=4), INTENT(IN) :: LGRID(NMAX,MMAX)
              INTEGER(KIND=4), INTENT(IN) :: LGRID2(NMAX,MMAX)
              REAL(KIND=4), INTENT(IN) :: XB(NMAX*MMAX)
              REAL(KIND=4), INTENT(IN) :: YB(NMAX*MMAX)
            END SUBROUTINE PLOTGRP
          END INTERFACE 
        END MODULE PLOTGRP__genmod
