        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 27 17:35:56 2016
        MODULE RDCCOL__genmod
          INTERFACE 
            SUBROUTINE RDCCOL(NMAX,MMAX,LUN,FNAM,FTYPE,LGRID,XBOTT,YBOTT&
     &,LUN2)
              INTEGER(KIND=4), INTENT(IN) :: MMAX
              INTEGER(KIND=4), INTENT(IN) :: NMAX
              INTEGER(KIND=4), INTENT(IN) :: LUN
              CHARACTER(*), INTENT(IN) :: FNAM
              CHARACTER(*), INTENT(IN) :: FTYPE(*)
              INTEGER(KIND=4), INTENT(IN) :: LGRID(NMAX,MMAX)
              REAL(KIND=4), INTENT(OUT) :: XBOTT(*)
              REAL(KIND=4), INTENT(OUT) :: YBOTT(*)
              INTEGER(KIND=4), INTENT(IN) :: LUN2
            END SUBROUTINE RDCCOL
          END INTERFACE 
        END MODULE RDCCOL__genmod
