        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 27 17:35:51 2016
        MODULE RDLGRI__genmod
          INTERFACE 
            SUBROUTINE RDLGRI(NFILES,LUNIT,FNAME,FTYPE)
              INTEGER(KIND=4), INTENT(IN) :: NFILES
              INTEGER(KIND=4), INTENT(INOUT) :: LUNIT(NFILES)
              CHARACTER(LEN=256), INTENT(INOUT) :: FNAME(NFILES)
              CHARACTER(LEN=20), INTENT(INOUT) :: FTYPE(2)
            END SUBROUTINE RDLGRI
          END INTERFACE 
        END MODULE RDLGRI__genmod
