        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 27 17:35:57 2016
        MODULE RDPART__genmod
          INTERFACE 
            SUBROUTINE RDPART(LUN1,LUN2,LNAM1)
              INTEGER(KIND=4), INTENT(IN) :: LUN1
              INTEGER(KIND=4), INTENT(IN) :: LUN2
              CHARACTER(LEN=256), INTENT(IN) :: LNAM1
            END SUBROUTINE RDPART
          END INTERFACE 
        END MODULE RDPART__genmod
