        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 27 17:35:54 2016
        MODULE RDWND__genmod
          INTERFACE 
            SUBROUTINE RDWND(LUNUT,SFILE,NMAX,MMAX,NOSEG,XB,YB,LGRIDA,  &
     &IERR)
              INTEGER(KIND=4), INTENT(IN) :: MMAX
              INTEGER(KIND=4), INTENT(IN) :: NMAX
              INTEGER(KIND=4), INTENT(IN) :: LUNUT
              CHARACTER(*), INTENT(IN) :: SFILE
              INTEGER(KIND=4), INTENT(IN) :: NOSEG
              REAL(KIND=4), INTENT(IN) :: XB(NMAX,MMAX)
              REAL(KIND=4), INTENT(IN) :: YB(NMAX,MMAX)
              INTEGER(KIND=4), INTENT(IN) :: LGRIDA(NMAX,MMAX)
              INTEGER(KIND=4), INTENT(OUT) :: IERR
            END SUBROUTINE RDWND
          END INTERFACE 
        END MODULE RDWND__genmod
