        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 27 17:35:52 2016
        MODULE REPORT_DATE_TIME__genmod
          INTERFACE 
            SUBROUTINE REPORT_DATE_TIME(LUN)
              INTEGER(KIND=4), INTENT(IN) :: LUN
            END SUBROUTINE REPORT_DATE_TIME
          END INTERFACE 
        END MODULE REPORT_DATE_TIME__genmod
