        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 27 17:35:23 2016
        MODULE ZOEKOPT__genmod
          INTERFACE 
            SUBROUTINE ZOEKOPT(MINP,VALUE,KEY,JA)
              INTEGER(KIND=4), INTENT(IN) :: MINP
              CHARACTER(*), INTENT(OUT) :: VALUE
              CHARACTER(*), INTENT(IN) :: KEY
              INTEGER(KIND=4), INTENT(OUT) :: JA
            END SUBROUTINE ZOEKOPT
          END INTERFACE 
        END MODULE ZOEKOPT__genmod
