
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = mpiaijf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE	 = libpetscmat
LOCDIR	 = src/mat/impls/aij/mpi/ftn-auto/
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
