
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = dadistf.c dainterpf.c dalocalf.c dagtonaf.c dacreatef.c gr1f.c daindexf.c fddaf.c daddf.c dageometryf.c dagetelemf.c dagtolf.c dagetarrayf.c dacornf.c dasubf.c dapreallocatef.c daf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetscdm
LOCDIR   = src/dm/impls/da/ftn-auto/
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
