
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib
CPPFLAGS  = ${PARMETIS_INCLUDE}
CFLAGS   =
FFLAGS   =
SOURCEC  = pmetisf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE   = libpetscmat
LOCDIR    = src/mat/partition/impls/pmetis/ftn-auto/
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
